### ISSUE TITLE
Use of existing reference store

### ISSUE THREAD

**Issue by aws-hyunmin** [aws-samples/amazon-omics-end-to-end-genomics#1]
Hi!

Could I use the existing of reference store in my account using this stack?

Because quota of reference store is only one. (not adjustable)
https://docs.aws.amazon.com/omics/latest/dev/load-balancer-limits.html

So, if the reference store is exist in account, this stack will raise the error. 

Thank you in advance!

**Comment by nbulsara** [comment]
Hi, yes we realize that this is a bit strict. I will add this to the list of requested features.
