### ISSUE TITLE
Regarding of paired-reads filename

### ISSUE THREAD

**Issue by aws-hyunmin** [aws-samples/amazon-omics-end-to-end-genomics#2]
Input S3 bucket (s3://bucket-name/inputs/)

![Screen Shot 2022-12-16 at 1 04 06 PM](https://user-images.githubusercontent.com/118273849/208019699-4f209086-427e-4eec-a2f5-17863e4fda4d.png)

In this case, it looks not work normally.
![Screen Shot 2022-12-16 at 1 07 59 PM](https://user-images.githubusercontent.com/118273849/208020013-b19046e8-c6f1-4cba-883d-1990bc824970.png)

**Comment by nbulsara** [comment]
Yes there is a known limitation where the reads have to be named a certain way. It's in the documentation too: 

Note that in this solution, the FASTQ files need to be named in the following manner:
    
<sample_name>_R1.fastq.gz 

<sample_name>_R2.fastq.gz

This can be updated to your needs by updating the Python regex in start_workflow_lambda.py

You can also use example FASTQs provided here to test:

s3://aws-genomics-static-us-east-1/omics-e2e/test_fastqs/NA1287820K_R1.fastq.gz
    
s3://aws-genomics-static-us-east-1/omics-e2e/test_fastqs/NA1287820K_R2.fastq.gz
