### ISSUE TITLE
Assistance with source FASTQ data

### ISSUE THREAD

**Issue by qb411** [aws-samples/amazon-omics-end-to-end-genomics#4]
Hi there, 

I'm very new to this processing backend.  I had attempted to use a trimmed fastq from the NIST datasource for my initial processing, but  think my understanding of FASTQ data sets is probably too low to understand what I'm missing.  I attempted to use a trimmeddata set as follows - [NIST7035_TAAGGCGA_L001_R1_001_trimmed.fastq.gz](ftp-trace.ncbi.nih.gov//ReferenceSamples/giab/data/NA12878/Garvan_NA12878_HG001_HiSeq_Exome/NIST7035_TAAGGCGA_L001_R1_001_trimmed.fastq.gz) for the initial run.  The error from the s3 bucket invoke lambda is as follows: 
<html>
<body>

2023-03-21T00:11:01.392-07:00CopyNot all FASTQs found for sample, exit | Not all FASTQs found for sample, exit
-- | --

</body>
</html>

Would it be possible to specify a representative patient sample to initially run through the workflow?  Or am I missing this from elsewhere in the guide?  

Appreciate the help!

**Comment by aws-hyunmin** [comment]
> Note that in this solution, the FASTQ files need to be named in the following manner:
>     
> <sample_name>_R1.fastq.gz 
> <sample_name>_R2.fastq.gz

I saw this note in README.md.
Can you confirm the file name in this manner?

**Comment by qb411** [comment]
Thanks for clarifying, yes I did miss the readme path for the 2 example files.  Appreciate the help on that! I was able to run the initial test without issue, but I've discovered a related problem.  I'll close this and open a new issue.
